[WIP]Nablarch依存箇所を明記し他FW利用者も使えるように変更
Fintan-contents/coding-standards pull request #1
Opened 2022-10-19 03:57 UTC by kumagoro1202

2022-10-21 08:29 UTC, backpaper0 requested changes

2022-10-21 08:29 UTC, backpaper0 commented on README.md
> +本リポジトリ内のドキュメントは[Fintan コンテンツ 使用許諾条項](https://fintan.jp/page/295/)の下に提供されています。
細かいけれど`https://fintan.jp/page/295/#Fintan%E3%82%B3%E3%83%B3%E3%83%86%E3%83%B3%E3%83%84%E4%BD%BF%E7%94%A8%E8%A8%B1%E8%AB%BE%E6%9D%A1%E9%A0%85`へリンクしておいた方が良いと思いました。

2022-10-21 08:29 UTC, backpaper0 commented on README.md
> +- [Javaコードフォーマッター](./java/assets/standard-code-formatter.xml/)
細かいけれど、末尾のスラッシュは要らないように思います（GitHub上では正しくリンクが生成されているので、閲覧する上では問題なさそうですが）。

2022-10-21 08:29 UTC, backpaper0 commented on java/java-style-guide.md
> +基本的に特定のフレームワークに限らず汎用的に使用できるようにしてありますが、[9. Nablarchライブラリ](#9nablarchライブラリ)については、[Nablarch Application Framework](https://nablarch.github.io/docs/LATEST/doc/index.html)を前提とした項目となります。他のフレームワークを利用される場合は項
ただの確認です。
ここでNablarchへ言及していますが、このリンクは https://fintan.jp/page/1868/ へ変更しなくても大丈夫ですか？

2022-10-21 08:29 UTC, backpaper0 commented on shell/README.md
> +この開発標準は[Nablarch](https://fintan.jp/page/1868/)が提供する[シェルスクリプト自動生成ツール](https://github.com/nablarch-development-standards/nablarch-development-standards-tools/tree/master/%E3%83%90%E3%83%83%E3%83%81%E9
シェルスクリプト自動生成ツールってシェルのテンプレートを修正すればNablarch以外のフレームワークでも使えないですかね？

もし使えないこともないのであれば「他のフレームワークを利用される場合は」ではなくて「シェルスクリプト自動生成ツールを使わない場合は」と表現してもいい気がしました。

2022-10-21 08:29 UTC, backpaper0 commented on sql/README.md
> +    - SQL_ID= で始まる点を除くとNablarch以外にも流用可能
わかりやすさのため「`SQL_ID〜「=」までは、単独行に記述する。`の一文のみNablarchを前提としている。それ以外はNablarch以外にも流用可能」ぐらい言い切っちゃっていい気がしました。

2022-10-21 08:29 UTC, backpaper0 commented
レビュー時間：1.0(h)

2022-10-24 02:25 UTC, kumagoro1202 commented on README.md
> +本リポジトリ内のドキュメントは[Fintan コンテンツ 使用許諾条項](https://fintan.jp/page/295/)の下に提供されています。
修正しました。

https://github.com/Fintan-contents/coding-standards/pull/1/commits/92d639a435bb8c7a31c7189b86f60229f4ed20d0

2022-10-24 02:25 UTC, kumagoro1202 commented on README.md
> +- [Javaコードフォーマッター](./java/assets/standard-code-formatter.xml/)
スラッシュ削除しました。

https://github.com/Fintan-contents/coding-standards/pull/1/commits/9f77785cde5486dba949ca0ac4d447df6d8e181a

2022-10-24 02:26 UTC, kumagoro1202 commented on java/java-style-guide.md
> +基本的に特定のフレームワークに限らず汎用的に使用できるようにしてありますが、[9. Nablarchライブラリ](#9nablarchライブラリ)については、[Nablarch Application Framework](https://nablarch.github.io/docs/LATEST/doc/index.html)を前提とした項目となります。他のフレームワークを利用される場合は項
他の部分でNablarchを参照する箇所はすべてFintanへのリンクになっていたのでここもFintanに変更しました。

https://github.com/Fintan-contents/coding-standards/pull/1/commits/519136dadcc6c0759de9d3cedaa9f7690db1acd0

2022-10-24 02:27 UTC, kumagoro1202 commented on shell/README.md
> +この開発標準は[Nablarch](https://fintan.jp/page/1868/)が提供する[シェルスクリプト自動生成ツール](https://github.com/nablarch-development-standards/nablarch-development-standards-tools/tree/master/%E3%83%90%E3%83%83%E3%83%81%E9
テンプレート修正すればつかえますね。表現見直しました。

https://github.com/Fintan-contents/coding-standards/pull/1/commits/680c7707c8737585b2fae1cd5cd4b5526c56976d

2022-10-24 02:27 UTC, kumagoro1202 commented on sql/README.md
> +    - SQL_ID= で始まる点を除くとNablarch以外にも流用可能
確かに仰る通りですね。修正しました。

https://github.com/Fintan-contents/coding-standards/pull/1/commits/5e38a166d0e179a340cb877b77637bc3b66d7295

2022-10-25 06:17 UTC, backpaper0 approved these changes

2022-10-25 06:29 UTC, merged