JSPスタイルガイドの文言をJakartaEE由来のものであることを追記
Fintan-contents/coding-standards pull request #24
Opened 2024-06-18 05:40 UTC by kankichi00

2024-06-19 09:40 UTC, kumagoro1202 requested changes

2024-06-19 09:40 UTC, kumagoro1202 commented on jsp/README.md
>  - [JSPコーディング規約.docx](./JSPコーディング規約.docx?raw=true)
[ガイドライン](https://jakarta.ee/legal/acronym_guidelines/)によると、ファイル名にJSPは使ってはいけないと読めます。ファイル名変えましょう。

> For names of Jakarta EE projects, specifications, test suites, and other related materials, the full project name/title and any scope statement should not incorporate an identified acronym.
> 
> OK: “Jakarta Message Service Specification”
> Not OK: “JMS Specification”
> Not OK: “Jakarta Message Service (JMS) Specification”

2024-06-19 11:45 UTC, tishijiri commented on jsp/README.md
>  - [JSPコーディング規約.docx](./JSPコーディング規約.docx?raw=true)
ファイル名は同意ですが他に気になることがあり、ファイル名を変えると、ファイル内で主な読み替え対象になってる「JSPコーディング規約」が少し違和感ありまして、ファイル名を「Jakarta Server Pagesコーディング規約」に変えるならファイル内の記載も変えるのがよさそうに思いました。

それとは別に、上記の点を対応すると残る読み替え対象は「JSP静的解析ツール」くらいになりそうで、それならスタイルガイドについては読み替えせずに全部変更した方がよいのか、ただそうするとシステム開発ガイドにもっていったときにバージョンアップしづらい（利用者が参考にしづらい）のではないか、と気になるところもあったので、方針について相談した方がよさそうです。

2024-06-20 00:39 UTC, tishijiri commented on jsp/README.md
>  - [JSPコーディング規約.docx](./JSPコーディング規約.docx?raw=true)
（相談した結果）ファイル名とファイル内のヘッダにある成果物名のみ変更し、それ以外は読み替えでいきましょう。

2024-06-20 05:19 UTC, kankichi00 commented on jsp/README.md
>  - [JSPコーディング規約.docx](./JSPコーディング規約.docx?raw=true)
修正しました。https://github.com/Fintan-contents/coding-standards/pull/24/commits/518018034dde84d6696e4267bd527f02966fc765

2024-06-20 05:32 UTC, kumagoro1202 approved these changes

2024-06-20 05:32 UTC, merged