使用不許可APIチェックツールの設定ファイルをnablarch-single-module-archetypeを参照するように変更
Fintan-contents/coding-standards pull request #25
Opened 2024-06-18 10:29 UTC by kankichi00

https://github.com/Fintan-contents/coding-standards/pull/23 で使用不許可APIチェックツール設定ファイルをJakartaEEに対応する中で、以下の理由から設定ファイルは`nablarch-single-module-archetype`を参照するように変更した。

- 設定ファイルはPJごとに必要なものを選択し、カスタマイズしながら使用するものなので、productとtestフォルダで置いておく必要がない（Nablarch以外にも使える想定＋あくまでNabalarchでの使用例）
- メンテナンスのしやすさ（更新忘れの防止）

2024-06-18 12:24 UTC, tishijiri commented on java/staticanalysis/unpublished-api/README.md
> +Nablarchでは、Javaコーディング規約に準拠した設定ファイルを以下のように格納しています。
「Nablarchでは〜」から始まると、Nablarchを使うのが前提のように見えてしまいました。
このスタイルガイド自体はNablarchに依存しないものとして公開しているので、Nablarchの紹介をする場合は「例えば、Nablarchを使用する場合には〜」みたいな感じで、例であることを明記してあげるのがよいと思います。

2024-06-18 12:30 UTC, tishijiri commented on java/staticanalysis/unpublished-api/README.md
> +※Java EE を使用する場合には、Jakarta EE を適宜読み替えてください。必要な設定ファイルは、[published-config(Java EE)](https://github.com/nablarch/nablarch-single-module-archetype/tree/master/nablarch-web/tools/static-analysis/spotbugs/
定義ファイルを読み替えるのが現実的ではない（実際に読み替えで済まないクラスもありそう）と思うので、`master`ではなく5系のタグで案内してあげるのがよいと思います。
ただ、5系のタグは今後も更新されうるため最新のタグ名も変わったとしても、その都度こちらを修正するのも避けたいので、Nablarch 5uXXではJava EEに対応していることを書いてその最新のタグを見るように文章で案内してあげるのがよいかなと思います。（リンクしたとしてもタグ一覧かな…一度書いてみてどういうのが見やすいかは見てみてほしいです）

2024-06-18 12:39 UTC, tishijiri commented on java/staticanalysis/unpublished-api/README.md
> +Nablarchでは、Javaコーディング規約に準拠した設定ファイルを以下のように格納しています。
あと「以下のように格納しています」だと格納方法（productionやtest）も案内してあげないと説明に違和感ありました。ちょっと落ち着いて推敲してみてはほしいけど、元の文章も使って例えば↓のような感じにして、

> 例えば、Nablarchが提供するブランクプロジェクトには、Javaコーディング規約に準拠した設定ファイルとして以下のファイルが同梱されています。

で、表を案内して、表の次に以下のような説明とかでしょうか。

> 設定ファイルはpublished-configに格納されていますので、これらを参考に自プロジェクトで必要な設定ファイルをご用意ください。

2024-06-19 02:35 UTC, kankichi00 commented on java/staticanalysis/unpublished-api/README.md
> +Nablarchでは、Javaコーディング規約に準拠した設定ファイルを以下のように格納しています。
例であることを明記し、文言を修正しました。https://github.com/Fintan-contents/coding-standards/pull/25/commits/95ffa407da2df74c8231e37da0c8c2eea349721f

2024-06-19 02:39 UTC, kankichi00 commented on java/staticanalysis/unpublished-api/README.md
> +※Java EE を使用する場合には、Jakarta EE を適宜読み替えてください。必要な設定ファイルは、[published-config(Java EE)](https://github.com/nablarch/nablarch-single-module-archetype/tree/master/nablarch-web/tools/static-analysis/spotbugs/
JavaEEの場合は文章でタグを見るように修正しました。
タグ一覧をリンクしても、タグ選択でpublished-configにすぐ行けるわけではなかったので微妙かなと思いました。説明としても簡略化するためにリンクは1つでタグを変更してもらうようにしました。https://github.com/Fintan-contents/coding-standards/pull/25/commits/95ffa407da2df74c8231e37da0c8c2eea349721f

2024-06-19 07:59 UTC, kumagoro1202 requested changes

2024-06-19 07:59 UTC, kumagoro1202 commented on java/staticanalysis/unpublished-api/README.md
> +例えば、Nablarchが提供するブランクプロジェクトには、Javaコーディング規約に準拠した設定ファイルとして以下のファイルが格納されています。
ツールの概要を説明している中に設定ファイルの個別の話が紛れ込んできている印象で違和感がある。
例えばというのも前の文章と繋がっておらず唐突な印象。この紹介丸ごとここから削除して設定方法のセクションに持っていってしまった方が良いのでは？

> **設定方法**
> ここでは、本ツールの設定ファイルの配置方法、記述方法を解説します。
> 
> **設定ファイル配置方法**
> 設定ファイルを格納したディレクトリ（以後、設定ファイルディレクトリ）には、複数の設定ファイル> を配置できます。 設定ファイルの拡張子は「config」としてください。
> 
> 例えば、Nablarchが提供するブランクプロジェクトには、Javaコーディング規約に準拠した設定ファイルとして以下のファイルが格納されています。

だと自然な感じではないですか？

2024-06-19 07:59 UTC, kumagoro1202 commented on java/staticanalysis/unpublished-api/README.md
> +※Java EE を使用する場合には、Jakarta EE を適宜読み替えてください。必要な設定ファイルは、[published-config(Java EE)](https://github.com/nablarch/nablarch-single-module-archetype/tree/master/nablarch-web/tools/static-analysis/spotbugs/
今後メンテナンスブランチとして作成される`v5-master`でもいいのではと思いました。5uXXの最新ブランチを参考にしてくださいとかで「5uXXの最新ブランチ」に`v5-master`のリンク貼るとか。

2024-06-19 07:59 UTC, kumagoro1202 commented on java/staticanalysis/unpublished-api/README.md
>  当ツールは、使用されている全てのAPIに対してチェックを実施します。
このセクション日本語がおかしい。

> 当ツールは、使用されている全てのAPIに対してチェックを実施します。 そのため、デフォルトで提供する設定ファイルのみでは、自プロジェクトで宣言しているAPIが使用不許可APIとして検知されます。
> 
> これを避けるには、自プロジェクトで宣言しているAPIを使用許可APIとする設定を行う必要があります。 自プロジェクト用の設定ファイルを設定ファイルディレクトリに配置し、自プロジェクトのパッケージを一意に特定できるパッケージを記述してください。
> 
> 例えば、プロジェクトにて作成する全てのパッケージがcom.example.projectで始まる場合、com.example.projectと記述したテキストファイルを1つ設定ファイルディレクトリに配置してください。

2024-06-19 07:59 UTC, kumagoro1202 commented on java/staticanalysis/unpublished-api/README.md
>  例えば、プロジェクトにて作成する全てのパッケージが`com.example.project`で始まる場合、`com.example.project`と記述したテキストファイルを1つ設定ファイルディレクトリに配置してください。
設定ファイル記述方法の1行目で「公開API」と記載があるが、ここまで使用許可/不許可APIという記載で語っているので、これも使用許可APIとして欲しい。

2024-06-19 07:59 UTC, kumagoro1202 commented on java/staticanalysis/unpublished-api/README.md
>  例えば、プロジェクトにて作成する全てのパッケージが`com.example.project`で始まる場合、`com.example.project`と記述したテキストファイルを1つ設定ファイルディレクトリに配置してください。
ここから後ろ公開するという言葉は全部使用許可にするに書き換えてほしい。

2024-06-20 04:59 UTC, kankichi00 commented on java/staticanalysis/unpublished-api/README.md
> +例えば、Nablarchが提供するブランクプロジェクトには、Javaコーディング規約に準拠した設定ファイルとして以下のファイルが格納されています。
Nablarchの例の紹介を設定方法のセクションに移動しました。https://github.com/Fintan-contents/coding-standards/pull/25/commits/5cc8db4801708465477c923c9f14fa3b8142ddc5

2024-06-20 05:00 UTC, kankichi00 commented on java/staticanalysis/unpublished-api/README.md
> +※Java EE を使用する場合には、Jakarta EE を適宜読み替えてください。必要な設定ファイルは、[published-config(Java EE)](https://github.com/nablarch/nablarch-single-module-archetype/tree/master/nablarch-web/tools/static-analysis/spotbugs/
v5-maseterのリンクに変更しました。https://github.com/Fintan-contents/coding-standards/pull/25/commits/5cc8db4801708465477c923c9f14fa3b8142ddc5

2024-06-20 05:01 UTC, kankichi00 commented on java/staticanalysis/unpublished-api/README.md
>  当ツールは、使用されている全てのAPIに対してチェックを実施します。
↓の内容を修正しました。https://github.com/Fintan-contents/coding-standards/pull/25/commits/5cc8db4801708465477c923c9f14fa3b8142ddc5

2024-06-20 05:02 UTC, kankichi00 commented on java/staticanalysis/unpublished-api/README.md
>  例えば、プロジェクトにて作成する全てのパッケージが`com.example.project`で始まる場合、`com.example.project`と記述したテキストファイルを1つ設定ファイルディレクトリに配置してください。
以下の通り表現を書き換えました。https://github.com/Fintan-contents/coding-standards/pull/25/commits/5cc8db4801708465477c923c9f14fa3b8142ddc5
公開API→使用許可API
公開する→使用許可する

2024-06-20 05:11 UTC, kumagoro1202 commented on java/staticanalysis/unpublished-api/README.md
> +※Java EE を使用する場合には、Jakarta EE を適宜読み替えてください。必要な設定ファイルは、[published-config(Java EE)](https://github.com/nablarch/nablarch-single-module-archetype/tree/master/nablarch-web/tools/static-analysis/spotbugs/
改めて見ると5uXXはちょっと変な感じしたので「Nablarchのプロダクトバージョン5(5、5u1、5u2・・・)ではJava EEを前提としているため、 Java EE を使用する場合は[Nablarch5の最新ブランチ](https://github.com/nablarch/nablarch-single-module-archetype/tree/v5-master/nablarch-web/tools/static-analysis/spotbugs/published-config)を参考にしてください。」とかが良いかなと思いました。

2024-06-20 05:17 UTC, kumagoro1202 commented on java/staticanalysis/unpublished-api/README.md
>  当ツールは、使用されている全てのAPIに対してチェックを実施します。
まだおかしいです。

> 当ツールは、使用されている全てのAPIに対してチェックを実施します。 そのため、デフォルトで提供する設定ファイルのみでは、自プロジェクトで宣言しているAPI ~~にもチェックしてしまいます。~~ **が使用不許可APIとして検知されます。**
> 
> これを避けるには、自プロジェクトで宣言しているAPIを使用許可する設定を行う必要があります。 ~~デフォルトの2つの設定ファイルとは別に、~~ 自プロジェクト用の設定ファイルを設定ファイルディレクトリに配置し、自プロジェクトのパッケージを一意に特定できるパッケージを記述してください。
> 
> 例えば、プロジェクトにて作成する全てのパッケージがcom.example.projectで始まる場合、com.example.projectと記述したテキストファイルを1つ設定ファイルディレクトリに配置してください。

2024-06-20 05:38 UTC, kankichi00 commented on java/staticanalysis/unpublished-api/README.md
> +※Java EE を使用する場合には、Jakarta EE を適宜読み替えてください。必要な設定ファイルは、[published-config(Java EE)](https://github.com/nablarch/nablarch-single-module-archetype/tree/master/nablarch-web/tools/static-analysis/spotbugs/
修正しました。https://github.com/Fintan-contents/coding-standards/pull/25/commits/39f3e45e17d965e06c6bbeda392fef37717e2d3d

2024-06-20 05:38 UTC, kankichi00 commented on java/staticanalysis/unpublished-api/README.md
>  当ツールは、使用されている全てのAPIに対してチェックを実施します。
修正しました。https://github.com/Fintan-contents/coding-standards/pull/25/commits/39f3e45e17d965e06c6bbeda392fef37717e2d3d

2024-06-20 05:47 UTC, kumagoro1202 approved these changes

2024-06-20 05:47 UTC, merged