ArchUnitのガイドを最新化（英語）
Fintan-contents/coding-standards pull request #4
Opened 2023-06-06 08:25 UTC by hiji

日本語版のコードサンプルから課題番号のソースコメントを誤って削除してしまっていたので、合わせて修正しました。

2023-06-06 08:46 UTC, kumagoro1202 requested changes

2023-06-06 08:46 UTC, kumagoro1202 commented on en/java/staticanalysis/archunit/docs/Ops-Rule.md
> +By specifying class name in the `doNotBelongToAnyOf` method, you can exclude the class in question and classes defined within the class in question from being tested.
この下の行は消し忘れ？

2023-06-06 08:46 UTC, kumagoro1202 commented on en/java/staticanalysis/archunit/docs/Ops-Rule.md
> +By specifying class name in the `doNotBelongToAnyOf` method, you can exclude the class in question and classes defined within the class in question from being tested.
重複してる？

2023-06-06 23:51 UTC, hiji commented on en/java/staticanalysis/archunit/docs/Ops-Rule.md
> +By specifying class name in the `doNotBelongToAnyOf` method, you can exclude the class in question and classes defined within the class in question from being tested.
すみません、作成途中のものが残っていましたので削除しました。

8d216a0d9ac64d87fdf0e87f43cd52c09aa7e35f

2023-06-06 23:52 UTC, hiji commented on en/java/staticanalysis/archunit/docs/Ops-Rule.md
> +By specifying class name in the `doNotBelongToAnyOf` method, you can exclude the class in question and classes defined within the class in question from being tested.
すみません、作成途中のものが残っていましたので削除しました。

8d216a0d9ac64d87fdf0e87f43cd52c09aa7e35f

2023-06-07 02:18 UTC, kumagoro1202 approved these changes

2023-06-07 02:18 UTC, merged