Javaコードフォーマッターのガイドを見直し（日本語）
Fintan-contents/coding-standards pull request #8
Opened 2023-06-09 08:57 UTC by hiji

以下の対応を実施しています。

- ガイドの目的は設定内容ではなく統一する重要性を伝えることであるため、内容を見直し
- Javaコードフォーマッターの設定ファイル提供を廃止
- 現在はEclipseよりもIntelliJ IDEAの方がシェアが大きいため、IntelliJ IDEAで設定する方法も案内する

2023-06-12 00:34 UTC, kumagoro1202 commented
TOPのREADMEにJavaコードフォーマッター設定ファイルへのリンクがあります。

2023-06-12 00:37 UTC, kumagoro1202 commented
[coding-standards/java/README.md](https://github.com/Fintan-contents/coding-standards/tree/NAB-533/verup-formatter/java/README.md)

> すぐに使えるコードフォーマッターを提供しています。

提供していますに違和感あります。

2023-06-12 00:50 UTC, kumagoro1202 requested changes

2023-06-12 00:50 UTC, kumagoro1202 commented on java/code-formatter.md
> +コーディング規約に準拠したコードスタイルをコードフォーマッターに設定し、プロジェクトで共有することで、コードスタイルを統一することができます。
コーディング規約の前提には

> 1.1.前提
> 本規約が対象とするコードは、次の3つが実施されていることを前提としています。

> 
> ・コードフォーマッターでフォーマットしていること（[Javaコードフォーマッター](https://github.com/Fintan-contents/coding-standards/blob/NAB-533/verup-formatter/java/code-formatter.md)）
> ・Checkstyleで機械的に検出できる規約違反は解消していること（[Checkstyleガイド](https://github.com/Fintan-contents/coding-standards/blob/NAB-533/verup-formatter/java/staticanalysis/checkstyle/README.md)）
> ・SpotBugsで明らかに問題のあるコードや、後々問題が発生しそうなコードを排除していること（[SpotBugsガイド](https://github.com/Fintan-contents/coding-standards/blob/NAB-533/verup-formatter/java/staticanalysis/spotbugs/README.md)）
> 機械的に対処できることは予め実施し、本規約ではより良いコードを書くためのガイド、あるいはコードレビューの指針となるように作成しました。

とあるので、「コーディング規約に準拠したコードスタイル」というのは違和感があります。
コードスタイルはコードフォーマッターに任せてしまって、コーディング規約ではより本質的な部分に注力するようにということを書いたほうがいいと思います。

2023-06-12 00:50 UTC, kumagoro1202 commented on java/code-formatter.md
> +コーディング規約に準拠したコードスタイルをコードフォーマッターに設定し、プロジェクトで共有することで、コードスタイルを統一することができます。
IDEのデフォルトも十分なフォーマットになってるから特にこだわりなければデフォルトのまま使うのがいいと案内するのがいいと思いました。フォーマットの内容より統一されていることが重要というニュアンスを強調するのがいいのかなと思います。
デフォルトのまま使うならエクスポート/インポートも必要ないので、開発者が参画時に最初に設定するよう案内しましょうと伝えると新米アーキテクトは助かるかなと思います。

2023-06-13 04:37 UTC, hiji commented on java/code-formatter.md
> +コーディング規約に準拠したコードスタイルをコードフォーマッターに設定し、プロジェクトで共有することで、コードスタイルを統一することができます。
説明を見直しました。

ecdf55a1a7f941307986163130dfea20d959d961

2023-06-13 04:37 UTC, hiji commented on java/code-formatter.md
> +コーディング規約に準拠したコードスタイルをコードフォーマッターに設定し、プロジェクトで共有することで、コードスタイルを統一することができます。
↑指摘と合わせて対応しました。

ecdf55a1a7f941307986163130dfea20d959d961

2023-06-13 04:38 UTC, hiji commented
> TOPのREADMEにJavaコードフォーマッター設定ファイルへのリンクがあります。

削除しました。

c0b0d2d9b679e5ab679a4bebf65464d93062d126

2023-06-13 04:38 UTC, hiji commented
> [coding-standards/java/README.md](https://github.com/Fintan-contents/coding-standards/tree/NAB-533/verup-formatter/java/README.md)
> 
> > すぐに使えるコードフォーマッターを提供しています。
> 
> 提供していますに違和感あります。

修正しました。

eac4842b6f90cfed2423b3cd8b7ec12aaf570b81

2023-06-13 05:05 UTC, kumagoro1202 approved these changes

2023-06-13 05:05 UTC, merged